version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/fuzz"
    schedule:
      interval: "weekly"
    groups:
      utoipa:
        patterns:
          - "utoipa"
          - "utoipa-axum"
      shared-cargo-dependencies:
        patterns:
          - "*"
        group-by: dependency-name
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
