[package]
name = "music-analysis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
music-application = { path = "../music-application", version = "0.1.0" }
rustfft.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tract-tensorflow.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
