[package]
name = "music-media"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
lofty.workspace = true
music-application = { path = "../music-application", version = "0.1.0" }
music-domain = { path = "../music-domain", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
serde-saphyr.workspace = true
same-file.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-util.workspace = true
uuid.workspace = true

[dev-dependencies]
base64.workspace = true
tempfile.workspace = true

[lints]
workspace = true
