use ts_rs::{Config, TS};

use crate::{
    AmbientState, ClientAction, CrossfadeType, DeviceInfo, ErrorCode, InterruptState, LoopMode,
    LoopingSfx, PlayerState, PositionReport, ServerMessage, ShuffleMode,
};

const FRONTEND_COMPATIBILITY_TYPES: &str = r#"
/**
 * Current clients always register protocol v2. Other action fields below are
 * optional precisely where the Rust decoder accepts an omitted value and
 * materializes its documented default.
 */
type OptionalFields<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>;

type FrontendClientAction<Action extends CanonicalClientAction> =
  Action extends { type: "register" }
    ? Omit<Action, "protocol_version"> & { protocol_version: 2 }
  : Action extends { type: "set_active_outputs" }
    ? OptionalFields<Action, "device_ids">
  : Action extends { type: "ambient_set_queue" }
    ? OptionalFields<Action, "track_ids">
  : Action extends { type: "ambient_enqueue" }
    ? OptionalFields<Action, "position">
  : Action extends { type: "ambient_skip_next" }
    ? OptionalFields<Action, "from_track_id">
  : Action extends { type: "ambient_play_playlist" }
    ? OptionalFields<Action, "start_index">
  : Action extends { type: "ambient_play_folder" }
    ? OptionalFields<Action, "path" | "start_index">
  : Action extends { type: "set_active_presets" }
    ? OptionalFields<Action, "preset_ids">
  : Action extends { type: "set_crossfade" }
    ? OptionalFields<Action, "crossfade_type">
  : Action extends { type: "fire_interrupt_track" }
    ? OptionalFields<Action, "return_to_ambient" | "fade_in_ms" | "fade_out_ms" | "duck_to">
  : Action extends { type: "fire_interrupt_playlist" }
    ? OptionalFields<Action, "return_to_ambient" | "fade_in_ms" | "fade_out_ms" | "duck_to">
  : Action extends { type: "interrupt_skip_next" }
    ? OptionalFields<Action, "from_track_id">
  : Action extends { type: "fire_sfx" }
    ? OptionalFields<Action, "volume">
  : Action extends { type: "start_loop" }
    ? OptionalFields<Action, "volume">
  : Action;

export type WsAction = FrontendClientAction<CanonicalClientAction>;

/**
 * These fields remain optional for one-deploy cached-client compatibility.
 * A current Rust server always emits them.
 */
export type AmbientState =
  Omit<CanonicalAmbientState, "position_anchored_at"> & {
    position_anchored_at?: number | null;
  };

export type InterruptState =
  Omit<CanonicalInterruptState, "position_anchored_at"> & {
    position_anchored_at?: number | null;
  };

export type PlayerState =
  Omit<CanonicalPlayerState, "position_epoch" | "default_device_volume" | "preset_revision" | "ambient" | "interrupt"> & {
    position_epoch?: number;
    default_device_volume?: number;
    preset_revision?: number;
    ambient: AmbientState;
    interrupt: InterruptState | null;
  };

type FrontendServerMessage<Message extends CanonicalServerMessage> =
  Message extends { type: "state_snapshot" }
    ? Omit<Message, "state"> & { state: PlayerState }
  : Message extends { type: "state_changed" }
    ? Omit<Message, "state"> & { state: PlayerState }
  : Message extends { type: "error" }
    ? Omit<Message, "code"> & { code?: ErrorCode | null }
  : Message;

export type WsMessage = FrontendServerMessage<CanonicalServerMessage>;
"#;

/// Render all browser-visible WebSocket bindings as one deterministic module.
///
/// The canonical declarations mirror Rust serialization. The small adapter
/// layer models decoder defaults and the deliberately supported cached-client
/// compatibility window, which are input/compatibility semantics rather than
/// serialization semantics.
#[must_use]
pub fn typescript_bindings() -> String {
    let config = Config::new().with_large_int("number");
    let declarations = [
        LoopMode::decl(&config),
        ShuffleMode::decl(&config),
        CrossfadeType::decl(&config),
        DeviceInfo::decl(&config),
        PositionReport::decl(&config),
        AmbientState::decl(&config),
        InterruptState::decl(&config),
        LoopingSfx::decl(&config),
        PlayerState::decl(&config),
        ErrorCode::decl(&config),
        ClientAction::decl(&config),
        ServerMessage::decl(&config),
    ]
    .map(|declaration| format!("export {declaration}"));

    format!(
        "// @generated by `music-cli contracts export`; DO NOT EDIT.\n\
         // Rust serialization is canonical; compatibility aliases are documented below.\n\n\
         {}\n{}",
        declarations.join("\n\n"),
        FRONTEND_COMPATIBILITY_TYPES.trim_start()
    )
}

#[cfg(test)]
mod tests {
    use super::typescript_bindings;

    #[test]
    fn bindings_are_stable_and_javascript_numeric() {
        let bindings = typescript_bindings();
        assert!(bindings.ends_with('\n'));
        assert!(bindings.contains("export type WsAction"));
        assert!(bindings.contains("export type WsMessage"));
        assert!(!bindings.contains("bigint"));
    }
}
